version: "3.4"

# Development environment override
services:
  php:
    volumes:
      - ./api:/srv/api:rw,cached
      - ./api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini
      # if you develop on Linux, you may use a bind-mounted host directory instead
      - ./api/var:/srv/api/var:rw
      - ./api/docker/php/supervisor.d/messenger-worker.ini:/etc/supervisor.d/messenger-worker.ini
    environment:
      APP_ENV: dev
    extra_hosts:
      - "host.docker.internal:host-gateway"

  caddy:
    volumes:
      - ./api/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api/public:/srv/api/public:ro

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
###< doctrine/doctrine-bundle ###

