framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: {}
        reset_on_message: true
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # sync: "sync://"
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    queue_name: default
                retry_strategy:
                    max_retries: 5
                    # milliseconds delay
                    delay: 5000
                    multiplier: 2
                    max_delay: 60000
        routing:
            App\Message\ApplyAnalysisMicroserviceOnArticleMessage: async
            App\Message\PostAnalysisProcessorMessage: async
            
        #routing:
        #    App\Message\AnalyzeArticle: async
            