controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation


authentication_token:
    path: /auth/login
    methods: ["POST"]
gesdinet_jwt_refresh_token:
    path: /auth/refresh_token
    methods: ["POST"]